"""``bootstrap_design_monorepo`` — initialize a fresh design monorepo.

This is the operation invoked when a user creates a new program (master
§3.1.6, "Create new program" wizard). It produces a freshly-initialised
git repository with:

- The framework's directory layout (``design/``, ``tools/``,
  ``agents/``, ``runs/``, ``.colony/``). Literature buckets are NOT
  scaffolded — operators declare ``knowledge_sources`` rows in
  ``.colony/repo_map.yaml`` pointing wherever they choose to organise
  papers / standards / books.
- ``.gitattributes`` registering the merge drivers (master §8.4) and
  the LFS filters (master §8.6).
- ``.gitignore`` excluding the runtime-only state.
- ``.colony/manifest.json`` (the one passed in).
- ``.colony/checkpoints.log`` (empty, ready to append).
- ``.colony/tool-registry.json`` (empty schema-versioned shell).
- A ``README.md`` stub identifying the program.
- A single bootstrap commit on ``main``.

The function is *additive* — if the directory already contains a git
repository, it raises rather than overwriting state. The caller is
responsible for choosing a fresh path.
"""

from __future__ import annotations

from collections.abc import Iterable
from datetime import datetime, timezone
from pathlib import Path

from .client import (
    DECISIONS_DIR,
    DesignMonorepoClient,
    DesignMonorepoError,
    MERGE_DRIVER_PATTERNS,
)
from .identity import AgentIdentity
from .manifest import DesignMonorepoManifest
from . import registry as registry_module


# Directories that ship with a fresh monorepo. ``.gitkeep`` files keep
# them tracked even when otherwise empty. The framework does not
# prescribe where literature lives — operators declare paths /
# acquirer destinations in ``.colony/repo_map.yaml`` and organise the
# tree however they like (``kb/literature/``, ``papers/``, anywhere
# under the repo root).
SCAFFOLD_DIRS: tuple[str, ...] = (
    "design/requirements",
    "design/decisions",
    "design/budgets",
    "design/evidence",
    "design/reports",
    "design/per-subsystem",
    "tools",
    "agents/policies",
    "agents/memories",
    "agents/traces",
    "runs",
    ".colony",
)


_LFS_PATTERNS: tuple[str, ...] = (
    "*.h5",
    "*.hdf5",
    "*.npy",
    "*.npz",
    "*.parquet",
    "*.zarr",
    "*.gz",
    "*.tar",
    "*.zip",
    "*.bin",
    "*.onnx",
    "*.safetensors",
    "*.ckpt",
    "*.pt",
    "*.pth",
    "*.stl",
    "*.step",
    "*.stp",
    "*.iges",
    "*.igs",
    "*.dwg",
    "*.dxf",
    "*.pdf",
    "agents/**/*.gz",
    "runs/**/*.h5",
    "runs/**/*.bin",
)


_GITIGNORE = """
# Local-only working state — never committed.
__pycache__/
*.pyc
*.pyo
.venv/
.env
.DS_Store
.idea/
.vscode/

# Build outputs from in-monorepo tools.
build/
dist/
*.egg-info/
target/

# Runtime caches that are not durable design state.
.cache/
.tmp/
.pytest_cache/
.mypy_cache/
.ruff_cache/

# Local CFD/FEM/EM scratch dirs (declare per-tool overrides as needed).
*.run/
""".lstrip()


def _gitattributes(driver_patterns: Iterable[tuple[str, str]] = MERGE_DRIVER_PATTERNS) -> str:
    lines: list[str] = [
        "# Generated by colony.design_monorepo.bootstrap. Edit with care.",
        "",
        "# Custom merge drivers per artifact type (master §8.4).",
        "# The driver *name* is committed; the per-clone *command* is",
        "# registered in `.git/config` by DesignMonorepoClient.install_merge_drivers.",
    ]
    for pattern, driver in driver_patterns:
        lines.append(f"{pattern} merge={driver}")
    lines.append("")
    lines.append("# LFS filters for binaries and large blobs (master §8.6).")
    for pattern in _LFS_PATTERNS:
        lines.append(f"{pattern} filter=lfs diff=lfs merge=lfs -text")
    lines.append("")
    return "\n".join(lines)


def _readme(manifest: DesignMonorepoManifest) -> str:
    return f"""# {manifest.program} — design monorepo

This repository is the authoritative durable design state for the
program **{manifest.program}** (target system: *{manifest.target_system}*),
operated by tenant **{manifest.tenant}** in colony **{manifest.colony}**.

It is managed by Polymathera Colony's design-automation framework. See
`colony_docs/markdown/apps/design_automation_architecture.md` and
`colony_docs/markdown/apps/git_as_design_state_engine.md` for the
discipline this monorepo follows. In short:

- `design/` is what's being designed.
- `tools/` is what the program built to design it.
- `agents/` is suspended agent state at quiescence boundaries.
- `runs/` is the run logs and simulation outputs we want to retain.
- `.colony/` is the framework's own metadata; do not hand-edit. The
  literature the design rests on is declared in
  `.colony/repo_map.yaml` `knowledge_sources:` rows — operators
  choose where it physically lives (e.g., `kb/literature/`).

Checkpoints are tags of the form `checkpoint/<iso8601>-<short_sha>`.
Forks are branches of the form `fork/<label>`. Both are produced and
managed by the framework's wrappers, not by hand.
"""


def bootstrap_design_monorepo(
    manifest: DesignMonorepoManifest,
    working_dir: Path,
    *,
    identity: AgentIdentity,
    initialize_lfs: bool = True,
) -> DesignMonorepoClient:
    """Create a fresh design monorepo at ``working_dir`` and commit it.

    The directory must be empty or non-existent. Returns a
    ``DesignMonorepoClient`` open on the new repo.

    The operation is local; pushing to ``manifest.design_repo_url`` is
    the caller's choice (the framework's deploy flow does it after
    validating remote write permissions).
    """

    from git import Repo

    working_dir = Path(working_dir)
    if working_dir.exists() and any(working_dir.iterdir()):
        raise DesignMonorepoError(
            f"{working_dir} is not empty; bootstrap requires a fresh path.",
        )
    working_dir.mkdir(parents=True, exist_ok=True)

    repo = Repo.init(str(working_dir), initial_branch=manifest.default_branch)

    # Make the repo aware of LFS *before* committing the .gitattributes
    # rules — `git lfs install` writes filter hooks into `.git/config`.
    if initialize_lfs:
        try:
            repo.git.lfs("install", "--local")
        except Exception:  # noqa: BLE001 - LFS may not be installed; degrade gracefully
            pass

    # Lay down the directory skeleton with `.gitkeep` placeholders.
    for sub in SCAFFOLD_DIRS:
        (working_dir / sub).mkdir(parents=True, exist_ok=True)
        keep = working_dir / sub / ".gitkeep"
        if not keep.exists():
            keep.write_text("", encoding="utf-8")

    # Top-level files.
    (working_dir / ".gitattributes").write_text(_gitattributes(), encoding="utf-8")
    (working_dir / ".gitignore").write_text(_GITIGNORE, encoding="utf-8")
    (working_dir / "README.md").write_text(_readme(manifest), encoding="utf-8")

    # `.colony/` metadata.
    manifest.write_path(working_dir)
    (working_dir / ".colony" / "checkpoints.log").write_text("", encoding="utf-8")
    registry_module.write_registry(working_dir, ())
    # Stash a small "bootstrap_at" marker so cross-session continuity
    # can compare against a known starting time.
    (working_dir / ".colony" / "bootstrap_at").write_text(
        datetime.now(timezone.utc).isoformat() + "\n",
        encoding="utf-8",
    )

    # Stage everything and commit under the agent's identity.
    client = DesignMonorepoClient(repo, manifest)
    client.install_merge_drivers()

    # Commit the bootstrap content.
    repo.git.add("-A")
    actor = identity.actor()
    repo.index.commit(
        f"bootstrap: {manifest.program} ({manifest.target_system})",
        author=actor,
        committer=actor,
    )

    # Now that there's an initial commit, set up imported remotes
    # (without fetching — the caller may not yet be online).
    client.setup_imported_remotes(fetch=False)
    return client


__all__ = ("bootstrap_design_monorepo", "SCAFFOLD_DIRS")
